/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultStats struct {
	Inbox int32 `json:"Inbox,omitempty"`
	Other int32 `json:"Other,omitempty"`
	Spam int32 `json:"Spam,omitempty"`
	NotDelivered int32 `json:"NotDelivered,omitempty"`
	InboxRate float32 `json:"InboxRate,omitempty"`
	SpamRate float32 `json:"SpamRate,omitempty"`
	BounceRate float32 `json:"BounceRate,omitempty"`
}
