/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultDnsblDnsbl struct {
	Server string `json:"Server,omitempty"`
	Status int32 `json:"Status,omitempty"`
	Txt string `json:"txt,omitempty"`
}
