/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultGoogleApps struct {
	Active bool `json:"Active,omitempty"`
	Finished bool `json:"Finished,omitempty"`
	Spam bool `json:"Spam,omitempty"`
	Phishy bool `json:"Phishy,omitempty"`
}
