/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultSpamAssassinHeaders struct {
	Score float32 `json:"Score,omitempty"`
	Tag string `json:"Tag,omitempty"`
	Description string `json:"Description,omitempty"`
}
