/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultSpamAssassin struct {
	Active bool `json:"Active,omitempty"`
	Finished bool `json:"Finished,omitempty"`
	Score float32 `json:"Score,omitempty"`
	Headers []ModelsTestresultSpamAssassinHeaders `json:"Headers,omitempty"`
}
