/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsGetprovider struct {
	Groups []ModelsGetproviderGroups `json:"Groups,omitempty"`
}
