/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresult struct {
	TestID string `json:"TestID,omitempty"`
	Created string `json:"Created,omitempty"`
	Finished bool `json:"Finished,omitempty"`
	DKIM string `json:"DKIM,omitempty"`
	SPF string `json:"SPF,omitempty"`
	Subject string `json:"Subject,omitempty"`
	MailFrom string `json:"MailFrom,omitempty"`
	Inboxes []ModelsTestresultInboxes `json:"Inboxes,omitempty"`
	SpamAssassin *ModelsTestresultSpamAssassin `json:"SpamAssassin,omitempty"`
	GoogleApps *ModelsTestresultGoogleApps `json:"GoogleApps,omitempty"`
	Barracuda *ModelsTestresultBarracuda `json:"Barracuda,omitempty"`
	Reason string `json:"Reason,omitempty"`
	ReasonExtra string `json:"ReasonExtra,omitempty"`
	SenderIP string `json:"SenderIP,omitempty"`
	SenderScore string `json:"SenderScore,omitempty"`
	SenderHostName string `json:"SenderHostName,omitempty"`
	Helo string `json:"Helo,omitempty"`
	ReturnPath string `json:"ReturnPath,omitempty"`
	ReverseHelo string `json:"ReverseHelo,omitempty"`
	ReverseIP string `json:"ReverseIP,omitempty"`
	DNSBL *ModelsTestresultDnsbl `json:"DNSBL,omitempty"`
	ExternalUserID string `json:"ExternalUserID,omitempty"`
	Meta string `json:"Meta,omitempty"`
	Stats *ModelsTestresultStats `json:"Stats,omitempty"`
}
