/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsGetproviderIsPs struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Domain string `json:"domain,omitempty"`
}
