/*
 * glockapps
 *
 * glock apps api for inboxing
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ModelsTestresultInboxes struct {
	ISP string `json:"ISP,omitempty"`
	IType string `json:"iType,omitempty"`
	Received string `json:"Received,omitempty"`
	Visible bool `json:"Visible,omitempty"`
	HeaderID string `json:"HeaderID,omitempty"`
	Delay string `json:"Delay,omitempty"`
}
